set_property IOSTANDARD LVCMOS18 [get_ports {green[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {green[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {green[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {blue[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {blue[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {red[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {red[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {red[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports hs]
set_property IOSTANDARD LVCMOS18 [get_ports mclk]
set_property IOSTANDARD LVCMOS18 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports vs]
set_property PACKAGE_PIN C7 [get_ports {blue[1]}]
set_property PACKAGE_PIN B7 [get_ports {blue[0]}]
set_property PACKAGE_PIN C6 [get_ports {green[0]}]
set_property PACKAGE_PIN B6 [get_ports {green[2]}]
set_property PACKAGE_PIN C5 [get_ports {red[2]}]
set_property PACKAGE_PIN A3 [get_ports {red[0]}]
set_property PACKAGE_PIN B4 [get_ports {red[1]}]
set_property PACKAGE_PIN B11 [get_ports hs]
set_property PACKAGE_PIN B12 [get_ports vs]
set_property PACKAGE_PIN E3 [get_ports mclk]
set_property PACKAGE_PIN C12 [get_ports reset]
set_property PACKAGE_PIN A5 [get_ports {green[1]}]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

set_property IOSTANDARD LVCMOS18 [get_ports EWGO]
set_property IOSTANDARD LVCMOS18 [get_ports EWwaiting]
set_property IOSTANDARD LVCMOS18 [get_ports NSGO]
set_property IOSTANDARD LVCMOS18 [get_ports NSwaiting]
set_property PACKAGE_PIN M17 [get_ports EWGO]
set_property PACKAGE_PIN P17 [get_ports NSGO]
set_property PACKAGE_PIN H17 [get_ports NSwaiting]
set_property PACKAGE_PIN K15 [get_ports EWwaiting]
