# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/bannisjack/VGA/VGA.cache/wt [current_project]
set_property parent.project_path C:/Users/bannisjack/VGA/VGA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  C:/Users/bannisjack/VGA/VGA.srcs/sources_1/new/Light_Controller.vhd
  C:/Users/bannisjack/VGA/VGA.srcs/sources_1/imports/new/Draw_Lights.vhd
  C:/Users/bannisjack/VGA/VGA.srcs/sources_1/imports/new/Moving_Block.vhd
  C:/Users/bannisjack/VGA/VGA.srcs/sources_1/imports/new/Intersection.vhd
  C:/Users/bannisjack/VGA/VGA.srcs/sources_1/new/top_module.vhd
}
read_xdc C:/Users/bannisjack/VGA/VGA.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/bannisjack/VGA/VGA.srcs/constrs_1/new/constraints.xdc]

synth_design -top top_module -part xc7a100tcsg324-1
write_checkpoint -noxdef top_module.dcp
catch { report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb }
